### PR TITLE
Enforce acceptable format on Team names

### PR DESCRIPTION
**Pull request by gigawhitlocks**
#### Summary
Mattermost team names must adhere to a fairly strict set of requirements and this PR conforms incoming Workspace names to the Team name format requirements. This code is copied directly from where Mattermost enforces its own requirements with very minor changes.

Note that this is just the URL name (the Team's "real" name), not the Display Name. In the current implementation the destination Display Name will be the normalized name that's valid as the URL and the user can change it to something friendlier after the import is complete.

Display Names have looser requirements and in a future version we might want to preserve the user's original workspace name with an additional piece of metadata but I didn't quickly locate where that input is sanitized in Mattermost so I wasn't sure what requirements to enforce on incoming Workspace names if they're mapped to the Team Display Name.

#### Ticket Link

No ticket

### CODE REVIEW

**Comment by gigawhitlocks** [comment]
Whoops! Had y'all as assignees for a second, wrong button! :man_facepalming:

**Review by Szymongib — APPROVED** [review]
LGTM although some tests would be much appreciated 🙂

**Comment by gigawhitlocks** [comment]
Yeah, you're not wrong, everything I've written recently needs them

**Comment by gigawhitlocks** [comment]
Though this particular routine is likely tested in Mattermost since it's nearly identical. I would've actually just used the one from Mattermost directly and only copy pasted to avoid having the whole Mattermost model as a dependency

**Review by gabrieljackson — APPROVED** [review]
LGTM!

**Pull request merged**
