### PR TITLE
Testing the AWAT Client

### PR DESCRIPTION
**Pull request by gigawhitlocks**
#### Summary

Changes related to testing the AWAT and the Import Supervisor in the Provisioner. These changes are needed for https://github.com/mattermost/mattermost-cloud/pull/439 

They will also be necessary for tests in this repo (coming soon!)

### CODE REVIEW

**Review by Szymongib — APPROVED** [review]
Could we add a Makefile rule to generate mocks? It is hard to remember commands when interface changes.

Also you can consider defining interface in Provisioner itself and generating mock there, I am not sure if it will be useful here as generally you will probably not need to mock external AWAT API when testing AWAT as it is most likely not calling itself though the external API (unless you want to use it for testing CLI).

**Comment by gigawhitlocks** [comment]
>Also you can consider defining interface in Provisioner itself and generating mock there...

Ha, it's funny that you called this out: I did consider this, and I couldn't decide where it was better. Since y'all think those mocks should be in the Provisioner, I'll move them there.

**Comment by gigawhitlocks** [comment]
OK I was able to move everything except the `Matcher` for one type to the Provisioner repo. I think this `Matcher` belongs in this repo anyway, as it should be useful for testing the AWAT as well.

**Review by Szymongib — APPROVED** [review]
👍

**Pull request merged**
