### PR TITLE
Bump golang and modules

### PR DESCRIPTION
**Pull request by stafot**
#### Summary
Bump golang and modules

#### Ticket Link
https://mattermost.atlassian.net/browse/CLD-7351

#### Release Note

```release-note
Bump golang and modules
```

### CODE REVIEW

**Review by angeloskyratzakos — APPROVED** [review]

**Comment by stafot** [comment]
@gabrieljackson I might need your help to adress some module updates here. Mostly mattermost-server dependency.

**Comment by stafot** [comment]
@gabrieljackson I believe that the problem is inherited from mmctl dependancies which ideally should be bumped and use latest mattermost server

**Comment by gabrieljackson** [comment]
Hey yeah, the `mmctl` and server dependency bump may be a breaking change. Let us know if you want our team to handle that part separately.

**Comment by stafot** [comment]
@gabrieljackson yes I will create a ticket.

**Review by gabrieljackson — APPROVED** [review]

**Pull request merged**
